default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development_instagram

test:
  <<: *default
  database: test_instagram

production:
  <<: *default
  database: production_instagram
